### ISSUE TITLE
Recommandation for digitization?

### ISSUE THREAD

**Issue by alix-tz** [PonteIneptique/wikicremma#3]
What would be yourrecommandations regarding how to digitize the document once we are done writing? You could leave entirely up to the writer (with the risk of receiving unusable files) or we can set a series of acceptable methods.

I would say: 
- cell phone pictures are ok as long as we stay above a minimum resolution and as long as attention is paid to the shadows
- scanner pictures are ok (either black and white or color, but not binarized)
- ... can you think of other methods?

Maybe we should have a series of good/bad examples 🤔

**Comment by PonteIneptique** [comment]
I thought that first, we'd try in place where we can get back the printed text (ENC, local libraries, friend groups) and digitize ourselves...

**Comment by alix-tz** [comment]
Alright, so let's re-open this issue when we expand! 🗺️
